### ISSUE TITLE
setup.py and pypi listing

### ISSUE THREAD

**Issue by jamescasbon** [jdoughertyii/PyVCF#4]
Can we get a setup.py and a pypi listing so that we can install from pip/easy_install and not have to manipulate python path?

A minimal setup.py that works: 

```
from setuptools import setup

setup(
    name='PyVCF',
    py_modules=['vcf'],
)
```

You will need to add a bit more to list on pypi, but then see: 
http://packages.python.org/an_example_pypi_project/setuptools.html#registering-your-project

**Comment by martijnvermaat** [comment]
You'd also need to add a license. Irrespective of pypi listing, I'd say that no one can really do anything with your code as long as it doesn't have a license.

**Comment by brentp** [comment]
@jdoughertyii would you rather we forked this project and developed there?

If so, @jamescasbon or @martijnvermaat want to have the main repo? I use this enough that
it'd be nice to have these contributions.

**Comment by jamescasbon** [comment]
If I must !

Or I think we can be added as collaborators on this project.

Is @jdoughertyii MIA?

**Comment by jdoughertyii** [comment]
Hi everyone,

Sorry for the lack of communication.  Here's the story: I coded this up one night on a whim, for a friend who never ended up wanting to use it.  Since I have nothing to do with biology, and I really never write code anymore, I basically forgot about this module.  That's also the reason I have no pypi listing/license --- this was essentially a one-off thing.  It was also an excuse to learn git.

I'm sort of shocked that anyone else finds this interesting, but I'd be more than happy to help out if people want to use it.  I will look into how to add collaborators.  @jamescasbon and/or @martijnvermaat, do you want to be added as collaborators?  Forking seems unnecessary, since the main branch isn't going anywhere any time soon.

**Comment by brentp** [comment]
@jdoughertyii it _is_ useful, and nicely done. can you add me as well?

**Comment by jamescasbon** [comment]
Actually, might be better to fork onto one of our accounts and manage it there - otherwise @jdoughertyii will be bombarded with notifications which he might not care for.

**Comment by martijnvermaat** [comment]
Whatever @jdoughertyii feels is most appropriate, I'm happy to sort of co-maintain either way.

Forgive me for pushing this, but I still think the next step should be for @jdoughertyii to choose a license :)

**Comment by jdoughertyii** [comment]
License: chosen and committed.  I think it makes sense to fork it, as @jamescasbon says, so that I don't get many notifications.  Let me know if there's anything else I can do.

**Comment by jamescasbon** [comment]
Thanks. @jdoughertyii will for soon (unless someone beats me to it)

**Comment by chapmanb** [comment]
Martijn, James and Brent;
Awesome that you are going to continue work on John's parser. It would be worth considering developing this as an Biopython module. It would be a nice contribution and you could get additional suggestions from that community.

**Comment by jamescasbon** [comment]
OK, I updated my fork and registered on pypi. 

@jdoughertyii you might want to put a note in your README pointing to https://github.com/jamescasbon/PyVCF

Pypi entry, now pip installable:
http://pypi.python.org/pypi/PyVCF/0.0.0
